#!/usr/bin/env node
/**
 * Copyright 2019-2021 Wingify Software Pvt. Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const run = require('./utils/run').run;

function runAll() {
  const tasks = [{
    name: 'Linting',
    command: 'composer run-script lint',
  }, /*{
    name: 'Code Sniffing',
    command: 'composer run-script phpcs',
  }, */{
    name: 'Code Beautifier Formatter',
    command: 'composer run-script phpcbf',
  }];

  for (let i = 0; i < tasks.length; i++) {
    run(tasks[i]);
  }
}

runAll();
